### ISSUE TITLE
date-calendar is broken on IE11

### ISSUE THREAD

**Issue by bastienguillon** [LuccaSA/lucca-front#979] opened 2020-04-09 09:28 UTC
This looks like a display problem: there's no error in the console

![image](https://user-images.githubusercontent.com/8553617/78879962-f2594680-7a54-11ea-8fd6-be25ef16949b.png)

http://lucca-front.lucca.local/master/ng/#/date-calendar

**Comment by sanlucca** [comment] 2020-05-19 15:18
Duplicate of #995

**Closed by sanlucca** 2020-05-19 15:18 UTC
Labels: bug, package ng
